name: Events Demo 1
on:
  pull_request:
    types: 
      - opened
  workflow_dispatch:
  issues:
    types:
      - opened

  push:
    branches:
      - main  # main
      - 'dev-*'  # dev-test dev-botton-new 
      - 'feat/**' # feat/botton/new
    paths:
      - '.github/workflows/*'
jobs:
  label_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Label the issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh auth login --with-token <<< "${GH_TOKEN}"
          gh issue edit ${{ env.ISSUE_NUMBER }} --add-label "triage"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."